### AI Talent Workshop - Day 2: Data Pre-processing and Feature Engineering

**Goal:** Practice data cleaning, transformation, and basic feature engineering on the merged AI talent data.

**Instructional Technique:** Jigsaw, Team-Based Problem Solving

**Materials:**
1.  **Interactive Notes:** Google Colaboratory Notebook 2 (will be shared)
2.  **Workshop:** Jupyter Notebook 2 (`AI_talent_workshop_part2.ipynb`) and the (potentially saved) merged dataset.

**Steps:**

1.  **(20 minutes):** Review the merged DataFrame from Wednesday and introduce various data pre-processing and feature engineering techniques using Google Colab Notebook 2.
2.  **(60 minutes):** You will work on Workshop 2 using the `AI_talent_workshop_part2.ipynb` notebook. You will be divided into three initial groups:
    * **Group A:** Focuses on identifying and handling missing values in the merged data.
    * **Group B:** Focuses on examining data types and performing any necessary cleaning or conversions (e.g., standardizing experience levels if needed).
    * **Group C:** Focuses on basic feature engineering – creating new relevant features from the existing data. For example, you might think about creating a feature that combines skills or flags highly experienced candidates.
    Each group will work on their assigned task.
3.  **(20 minutes):** You will form new teams with at least one member from each of the initial groups. Each member will share their findings and the code they used. Your new team will then collaboratively discuss the impact of each pre-processing step and explore further feature engineering possibilities relevant to identifying top AI talent.
4.  **(10 minutes):** Final group discussion where each team shares their insights on the pre-processing and feature engineering steps, and we discuss how these steps prepare the data for potential machine learning models.

In [1]:
# -*- coding: utf-8 -*-
import pandas as pd

# Load the merged data (assuming it's been saved or re-loaded)
try:
    merged_df = pd.read_csv('data\merged_ai_data.csv') # Assuming you saved it after merging
except FileNotFoundError:
    try:
        profiles_df = pd.read_csv('candidate_profiles.csv')
        assessments_df = pd.read_csv('technical_assessments.csv')
        if not profiles_df.empty and not assessments_df.empty and 'CandidateID' in profiles_df.columns and 'CandidateID' in assessments_df.columns:
            merged_df = pd.merge(profiles_df, assessments_df, on='CandidateID', how='left')
            print("Data merged.")
        else:
            merged_df = pd.DataFrame()
    except FileNotFoundError:
        print("Error: Could not load candidate profiles or technical assessments.")
        merged_df = pd.DataFrame()

if not merged_df.empty:
    # --- Task 1 (Group A): Handling Missing Values ---
    print("\n--- Task 1 (Group A): Handling Missing Values ---")
    print("\nInitial missing values:\n", merged_df.isnull().sum())
    # Students in Group A will implement their strategy here

    # --- Task 2 (Group B): Data Type Conversion and Cleaning ---
    print("\n--- Task 2 (Group B): Data Type Conversion and Cleaning ---")
    print("\nData types:\n", merged_df.dtypes)
    # Students in Group B will work on data type issues and potential cleaning (e.g., experience levels)

    # --- Task 3 (Group C): Feature Engineering ---
    print("\n--- Task 3 (Group C): Feature Engineering ---")
    # Students in Group C will create new features from existing ones

    # --- Collaborative Task (All Teams) ---
    print("\n--- Collaborative Task (All Teams) ---")
    # Teams will discuss the impact of the pre-processing steps and potentially engineer more features or analyze the data.

    # Example collaborative tasks (to be expanded by students):
    if 'Years of Experience' in merged_df.columns and 'Assessment Score' in merged_df.columns:
        # Example: Create a boolean feature for "Experienced" candidates
        merged_df['Experienced'] = merged_df['Years of Experience'] > 3
        print("\nDataFrame with 'Experienced' feature:")
        print(merged_df[['CandidateID', 'Years of Experience', 'Experienced']].head())

        # Example: Analyze the relationship between experience and assessment score (briefly)
        print("\nCorrelation between Years of Experience and Assessment Score:")
        print(merged_df[['Years of Experience', 'Assessment Score']].corr())

--- Task 1 (Group A): Handling Missing Values ---

Initial missing values:
 CandidateID            0
Name                   0
Years of Experience    0
Skills                 0
AssessmentID           1
Assessment Score       1
Topic                  1
dtype: int64

--- Task 2 (Group B): Data Type Conversion and Cleaning ---

Data types:
 CandidateID              int64
Name                       str
Years of Experience      int64
Skills                     str
AssessmentID               str
Assessment Score       float64
Topic                      str
dtype: object

--- Task 3 (Group C): Feature Engineering ---

--- Collaborative Task (All Teams) ---

DataFrame with 'Experienced' feature:
   CandidateID  Years of Experience  Experienced
0            1                    5         True
1            1                    5         True
2            2                    2        False
3            3                    8         True
4            3                    8         True

Correlation between Years of Experience and Assessment Score:
                     Years of Experience  Assessment Score
Years of Experience              1.00000           0.82112
Assessment Score                 0.82112           1.00000

## Inspecting Merged Dataset

In [ ]:
print("Dataset shape:", merged_df.shape)

print("\nColumn names:")
print(merged_df.columns.tolist())

print("\nData types:")
print(merged_df.dtypes)

print("\nMissing values:")
print(merged_df.isnull().sum())

print("\nFirst 5 rows:")
display(merged_df.head())

Dataset shape: (15, 8)

Column names:
['CandidateID', 'Name', 'Years of Experience', 'Skills', 'AssessmentID', 'Assessment Score', 'Topic', 'Experienced']

Data types:
CandidateID              int64
Name                       str
Years of Experience      int64
Skills                     str
AssessmentID               str
Assessment Score       float64
Topic                      str
Experienced               bool
dtype: object

Missing values:
CandidateID            0
Name                   0
Years of Experience    0
Skills                 0
AssessmentID           1
Assessment Score       1
Topic                  1
Experienced            0
dtype: int64

First 5 rows:

,CandidateID,Name,Years of Experience,Skills,AssessmentID,Assessment Score,Topic,Experienced
0,1,Alice,5,"Python, TensorFlow, NLP",A101,85.0,Python,True
1,1,Alice,5,"Python, TensorFlow, NLP",A108,79.0,TensorFlow,True
2,2,Bob,2,"Java, Machine Learning",A104,78.0,Machine Learning,False
3,3,Charlie,8,"Python, Deep Learning, Computer Vision",A102,92.0,Deep Learning,True
4,3,Charlie,8,"Python, Deep Learning, Computer Vision",A110,90.0,Computer Vision,True

In [4]:
merged_df["AssessmentID"].value_counts(dropna=False)

AssessmentID
A101    1
A108    1
A104    1
A102    1
A110    1
A107    1
A103    1
A114    1
A111    1
A105    1
A112    1
A109    1
A106    1
A113    1
NaN     1
Name: count, dtype: int64

In [5]:
merged_df["Assessment Score"].value_counts(dropna=False)

Assessment Score
90.0    2
85.0    1
79.0    1
78.0    1
92.0    1
82.0    1
88.0    1
91.0    1
75.0    1
89.0    1
86.0    1
95.0    1
81.0    1
NaN     1
Name: count, dtype: int64

## Handling missing values
Missing values appear in:
- AssessmentID
- Assessment Score
- Topic

In [7]:
processed_df = merged_df.copy()

# Fill missing assessment information
processed_df['AssessmentID'] = processed_df['AssessmentID'].fillna('A115')

processed_df['Topic'] = processed_df['Topic'].fillna('No Assessment')

# Calculate the mean Assessment Score
mean_score = processed_df['Assessment Score'].mean()

# Round mean to 2 significant figures
mean_score_2sf = float(f"{mean_score:.2g}")

# Replace missing Assessment Score with the 2-significant-figure mean
processed_df['Assessment Score'] = (
    processed_df['Assessment Score'].fillna(mean_score_2sf)
)

print("Mean Assessment Score used:", mean_score_2sf)

print("\nMissing values after handling:")
print(processed_df.isnull().sum())

Mean Assessment Score used: 86.0

Missing values after handling:
CandidateID            0
Name                   0
Years of Experience    0
Skills                 0
AssessmentID           0
Assessment Score       0
Topic                  0
Experienced            0
dtype: int64

In [11]:
# Convert numeric columns to numeric data types

processed_df['CandidateID'] = pd.to_numeric(
    processed_df['CandidateID'],
    errors='coerce'
)

processed_df['Years of Experience'] = pd.to_numeric(
    processed_df['Years of Experience'],
    errors='coerce'
)

processed_df['Assessment Score'] = pd.to_numeric(
    processed_df['Assessment Score'],
    errors='coerce'
)

# Convert text columns to string
processed_df['Name'] = processed_df['Name'].astype(str)
processed_df['Skills'] = processed_df['Skills'].astype(str)
processed_df['AssessmentID'] = processed_df['AssessmentID'].astype(str)
processed_df['Topic'] = processed_df['Topic'].astype(str)

print(processed_df.dtypes)

CandidateID              int64
Name                       str
Years of Experience      int64
Skills                     str
AssessmentID               str
Assessment Score       float64
Topic                      str
Experienced               bool
dtype: object

In [12]:
# Check for completely duplicated rows

duplicate_count = processed_df.duplicated().sum()

print("Number of completely duplicated rows:", duplicate_count)

Number of completely duplicated rows: 0

In [13]:
processed_df = processed_df.drop_duplicates()

print("Dataset shape after removing exact duplicates:", processed_df.shape)

Dataset shape after removing exact duplicates: (15, 8)

In [14]:
# Create an Experienced feature

processed_df['Experienced'] = processed_df['Years of Experience'] >= 3

print(
    processed_df[
        ['CandidateID', 'Years of Experience', 'Experienced']
    ].head(10)
)

   CandidateID  Years of Experience  Experienced
0            1                    5         True
1            1                    5         True
2            2                    2        False
3            3                    8         True
4            3                    8         True
5            4                    3         True
6            5                    6         True
7            5                    6         True
8            6                    1        False
9            7                    4         True

In [15]:
# Create experience categories

def categorize_experience(years):
    if years < 2:
        return 'Junior'
    elif years < 5:
        return 'Mid-Level'
    else:
        return 'Senior'

processed_df['Experience Level'] = (
    processed_df['Years of Experience']
    .apply(categorize_experience)
)

print(
    processed_df[
        ['Years of Experience', 'Experience Level']
    ].drop_duplicates().sort_values('Years of Experience')
)

    Years of Experience Experience Level
8                     1           Junior
2                     2        Mid-Level
5                     3        Mid-Level
9                     4        Mid-Level
0                     5           Senior
6                     6           Senior
10                    7           Senior
3                     8           Senior
12                    9           Senior

In [16]:
# Create assessment performance categories

def categorize_score(score):
    if score >= 80:
        return 'Excellent'
    elif score >= 70:
        return 'Good'
    elif score >= 50:
        return 'Average'
    else:
        return 'Needs Improvement'

processed_df['Assessment Performance'] = (
    processed_df['Assessment Score']
    .apply(categorize_score)
)

print(
    processed_df[
        ['Assessment Score', 'Assessment Performance']
    ].head(10)
)

   Assessment Score Assessment Performance
0              85.0              Excellent
1              79.0                   Good
2              78.0                   Good
3              92.0              Excellent
4              90.0              Excellent
5              82.0              Excellent
6              88.0              Excellent
7              91.0              Excellent
8              75.0                   Good
9              90.0              Excellent

In [17]:
# Identify highly experienced and high-performing candidates

processed_df['High Potential'] = (
    (processed_df['Years of Experience'] >= 5) &
    (processed_df['Assessment Score'] >= 80)
)

print(
    processed_df[
        [
            'CandidateID',
            'Years of Experience',
            'Assessment Score',
            'High Potential'
        ]
    ].head(10)
)

   CandidateID  Years of Experience  Assessment Score  High Potential
0            1                    5              85.0            True
1            1                    5              79.0           False
2            2                    2              78.0           False
3            3                    8              92.0            True
4            3                    8              90.0            True
5            4                    3              82.0           False
6            5                    6              88.0            True
7            5                    6              91.0            True
8            6                    1              75.0           False
9            7                    4              90.0           False

In [18]:
# Calculate correlation

correlation = processed_df[
    ['Years of Experience', 'Assessment Score']
].corr()

print("Correlation Matrix:")
display(correlation)

print(
    f"\nCorrelation between experience and assessment score: "
    f"{correlation.loc['Years of Experience', 'Assessment Score']:.4f}"
)

Correlation Matrix:

                     Years of Experience  Assessment Score
Years of Experience             1.000000          0.821131
Assessment Score                0.821131          1.000000

Correlation between experience and assessment score: 0.8211

In [19]:
print("=== Experience Level Distribution ===")
print(processed_df['Experience Level'].value_counts())

print("\n=== Assessment Performance Distribution ===")
print(processed_df['Assessment Performance'].value_counts())

print("\n=== High Potential Candidates ===")
print(processed_df['High Potential'].value_counts())

=== Experience Level Distribution ===
Experience Level
Senior       9
Mid-Level    5
Junior       1
Name: count, dtype: int64

=== Assessment Performance Distribution ===
Assessment Performance
Excellent    12
Good          3
Name: count, dtype: int64

=== High Potential Candidates ===
High Potential
True     8
False    7
Name: count, dtype: int64

In [20]:
print("=== Numerical Summary ===")

display(
    processed_df[
        ['Years of Experience', 'Assessment Score']
    ].describe()
)

=== Numerical Summary ===

       Years of Experience  Assessment Score
count            15.000000         15.000000
mean              4.933333         85.800000
std               2.433888          5.747049
min               1.000000         75.000000
25%               3.000000         81.500000
50%               5.000000         86.000000
75%               6.500000         90.000000
max               9.000000         95.000000

In [21]:
print("Final processed dataset:")
display(processed_df.head(10))

print("\nFinal dataset shape:", processed_df.shape)

print("\nFinal columns:")
print(processed_df.columns.tolist())

Final processed dataset:

,CandidateID,Name,Years of Experience,Skills,AssessmentID,Assessment Score,Topic,Experienced,Experience Level,Assessment Performance,High Potential
0,1,Alice,5,"Python, TensorFlow, NLP",A101,85.0,Python,True,Senior,Excellent,True
1,1,Alice,5,"Python, TensorFlow, NLP",A108,79.0,TensorFlow,True,Senior,Good,False
2,2,Bob,2,"Java, Machine Learning",A104,78.0,Machine Learning,False,Mid-Level,Good,False
3,3,Charlie,8,"Python, Deep Learning, Computer Vision",A102,92.0,Deep Learning,True,Senior,Excellent,True
4,3,Charlie,8,"Python, Deep Learning, Computer Vision",A110,90.0,Computer Vision,True,Senior,Excellent,True
5,4,David,3,"R, Statistics, Data Analysis",A107,82.0,Statistics,True,Mid-Level,Excellent,False
6,5,Eve,6,"Python, PyTorch, Reinforcement Learning",A103,88.0,PyTorch,True,Senior,Excellent,True
7,5,Eve,6,"Python, PyTorch, Reinforcement Learning",A114,91.0,Reinforcement Learning,True,Senior,Excellent,True
8,6,Frank,1,"SQL, Data Engineering",A111,75.0,SQL,False,Junior,Good,False
9,7,Grace,4,"Python, Cloud Computing, ML Ops",A105,90.0,ML Ops,True,Mid-Level,Excellent,False

Final dataset shape: (15, 11)

Final columns:
['CandidateID', 'Name', 'Years of Experience', 'Skills', 'AssessmentID', 'Assessment Score', 'Topic', 'Experienced', 'Experience Level', 'Assessment Performance', 'High Potential']

In [22]:
import os

# Make sure the data folder exists
os.makedirs('data', exist_ok=True)

# Save the processed dataset
processed_df.to_csv(
    'data/processed_ai_data.csv',
    index=False
)

print("Processed dataset saved to: data/processed_ai_data.csv")

Processed dataset saved to: data/processed_ai_data.csv